/*

JSON Web Token (JWT)


A JSON Web Token (JWT) is an open standard (RFC 7519) used to securely transmit information between parties as a JSON object. It is primarily used for authentication (verifying who you are) and authorization (checking what you are allowed to access) in web applications

Instead of storing user sessions on a server (which takes up database memory and scales poorly), the server generates a digitally signed JWT and sends it to the client. The client sends this token with every subsequent request, allowing the server to securely identify the user without querying the database

A JWT is made up of three parts, separated by dots (.), and looks like this: 

xxxxx.yyyyy.zzzzz
•  Header (xxxxx): Contains metadata about the token, such as the type (JWT) and the cryptographic algorithm used for the signature (e.g., HS256).

•  Payload (yyyyy): Contains the "claims," which are pieces of information like user data (e.g., userId, role) and expiration times (e.g., exp).

•  Signature (zzzzz): Generated by combining the encoded header, payload, and a secret key. This verifies that the sender is who they say they are and ensures the token wasn't tampered with along the way


HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  secret)

*/

const jwtLibrary = require('jsonwebtoken');

/* Encode */
/*
// The only arguments we need are a secret value and some JSON
const json = {"id": "1", "name": "raj"}
const secret = "rajjjjj";

// Ignore the options for now, we'll check them later
const jwt = jwtLibrary.sign(json, secret);

console.log("JWT:", jwt);
*/

/* Decode */

// From previous example
const jwt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYW1lIjoicmFqIiwiaWF0IjoxNzgwMjEyNjI3fQ.VqAYqWM8WKJ9dZG5ccqI2jG1prOBmCILa-kLWQdK5Ho";
const secret = "rajjjjj";

// Ignore the options for now, we'll check them later
const verifyResult = jwtLibrary.verify(jwt, secret);

console.log("verifyResult:", verifyResult);
// verifyResult: { key: 'value', key2: 'value2', iat: 1634178110 }






/*
//Anyone can view the contents of a JWT, even without the secret#
// From previous example
const jwt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJ2YWx1ZSIsImtleTIiOiJ2YWx1ZTIiLCJpYXQiOjE2MzQxNzgxMTB9.vnXM0oxw05QH1Vs6RsvYp6LaEqFFqZ-NExQMXBgP7Mk";

const decodeResult = jwtLibrary.decode(jwt);
console.log("decodeResult:", decodeResult);
// decodeResult: { key: 'value', key2: 'value2', iat: 1634178110 }


*/